name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  BUILD: Explore
  VERSION: Dev Edition


jobs:
  CreateCursePack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build.sh
        run: bash build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD }}-${{ env.VERSION }}.${{ github.run_number }}
          path: artifacts
